Create model student
bgonzalezcbcv/cb-api pull request #6
Opened 2022-09-06 22:07 UTC by Usuca

2022-09-06 22:12 UTC, NicolasBlumetto commented on db/migrate/20220906001245_create_students.rb
> +      t.datetime :vaccine_expiry
typo

2022-09-06 22:15 UTC, NicolasBlumetto commented on db/migrate/20220906001245_create_students.rb
> +      t.string :tuition
Cambiar a horario con rango de horas.

2022-09-12 18:56 UTC, marcobaldi97 commented on app/models/student.rb
> +  validates :birthplace, :birthdate, :nacionality, :first_language, presence: true
typo in nacionality, correct: nationality

2022-09-12 18:59 UTC, marcobaldi97 commented on app/controllers/api/students_controller.rb
> +    )
Falta el email, también tomar en cuenta que el form que hacen los padres tienen solo nombres y apellidos en vez de primer y segundo nombres y apellidos.

2022-09-12 19:07 UTC, marcobaldi97 commented on db/migrate/20220906001245_create_students.rb
> +      t.string :vaccine_name
Que es vaccine_name? No está en el formulario...

2022-09-12 19:09 UTC, ignacio-carmona commented on test/fixtures/family_members.yml
> +  rol: MyString
rol -> role, si es lo que yo pienso que es
```suggestion
  role: MyString
```

2022-09-12 19:10 UTC, marcobaldi97 commented on app/controllers/api/students_controller.rb
> +    )
Faltan la info de los familiares no?

2022-09-12 19:10 UTC, ignacio-carmona commented on test/fixtures/family_members.yml
> +  rol: MyString
```suggestion
  role: MyString
```

2022-09-12 19:12 UTC, marcobaldi97 commented on app/controllers/api/students_controller.rb
> +    )
https://docs.google.com/spreadsheets/d/1tB7n1G3qzmZi-S7sl6hqCPitReJhhAMN/edit?usp=drive_web&ouid=111227055161628393201&rtpof=true verifiquen que esta API tiene como mínimo **todos los campos** que hay en este formulario

2022-09-12 19:13 UTC, ignacio-carmona commented on test/fixtures/administrative_infos.yml
> +  enrollmentDate: 2022-09-08 03:24:18
hay mezclado camelCase con separación con _ en los nombres de las cosas. Estaría bueno que se unificara en lo posible

2022-09-12 19:13 UTC, marcobaldi97 requested changes
Lo que deje de comentarios.

2022-09-12 19:19 UTC, marcobaldi97 commented on db/schema.rb
> +  end
Falta telefono, email

2022-09-12 19:45 UTC, Usuca commented on db/migrate/20220906001245_create_students.rb
> +      t.string :vaccine_name
nombre de la vacuna, esta en la información básica

2022-09-13 18:42 UTC, marcobaldi97 commented on db/migrate/20220906001245_create_students.rb
> +      t.string :scheduler_end
schedule en vez de scheduler

2022-09-13 18:43 UTC, marcobaldi97 commented on db/migrate/20220906001245_create_students.rb
> +      t.string :office
¿Qué es este "office"?

2022-09-13 18:45 UTC, marcobaldi97 commented on db/migrate/20220906001245_create_students.rb
> +      t.string :vaccine_name
Si hablas del campo en (B26) https://docs.google.com/spreadsheets/d/1c0ZFm3J-52D4IXtabaDT64R3XUPJQQZr/edit#gid=636950830
creo que se habia quedado que esto es la fecha de venicimiento de la primera vacuna a vencerse.

2022-09-13 22:09 UTC, Usuca commented on db/migrate/20220906001245_create_students.rb
> +      t.string :vaccine_name
Si, solo la fecha? no importa el nombre de la vacuna? Entiendo que solo va la primera vacuna en vencerse, pero no vamos a poner cual es?

2022-09-13 22:09 UTC, Usuca commented on test/fixtures/family_members.yml
> +  rol: MyString
ya no existe el archivo, creo

2022-09-13 22:13 UTC, Usuca commented on db/migrate/20220906001245_create_students.rb
> +      t.string :scheduler_end
updated

2022-09-13 22:15 UTC, Usuca commented on db/migrate/20220906001245_create_students.rb
> +      t.string :office
Campo B23 - https://docs.google.com/spreadsheets/d/12lNZ7kTULpMWazNXwu1n0u6DydaXf1Sf/edit#gid=1826085753

2022-09-14 21:23 UTC, bgonzalezcbcv commented on db/migrate/20220906001245_create_students.rb
> +      t.string :vaccine_name
De la vacuna solo importa la fecha, le planteamos esto de usar el nombre a ellos?

2022-09-14 21:24 UTC, santiagosegundo96 commented on db/migrate/20220906001245_create_students.rb
> +      t.string :vaccine_name
De la vacuna solo importa la fecha, le planteamos esto de usar el nombre a ellos?

2022-09-14 22:49 UTC, Usuca commented on db/migrate/20220906001245_create_students.rb
> +      t.string :vaccine_name
lo dejamos opcional

2022-09-14 23:22 UTC, marcobaldi97 commented on db/migrate/20220906001245_create_students.rb
> +      t.string :office
Ok

2022-09-15 19:51 UTC, marcobaldi97 approved these changes

2022-09-15 21:35 UTC, merged